import "@/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Lora, Nunito } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";

import { TooltipProvider } from "@/components/ui/tooltip";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap",
});

const lora = Lora({
	subsets: ["latin"],
	variable: "--font-lora",
	display: "swap",
});

const nunito = Nunito({
	subsets: ["latin"],
	variable: "--font-rounded",
	display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-jetbrains-mono",
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			className={`${inter.variable} ${lora.variable} ${nunito.variable} ${jetbrainsMono.variable}`}
			lang="en"
		>
			<body>
				<ClerkProvider>
					<NuqsAdapter>
						<TRPCReactProvider>
							<TooltipProvider>
								{children}
								<Toaster position="top-center" richColors />
							</TooltipProvider>
						</TRPCReactProvider>
					</NuqsAdapter>
				</ClerkProvider>
			</body>
		</html>
	);
}
