import type { PublicWishlistViewModel } from "@/server/mappers/view-models";

/**
 * Static fixture for the marketing landing's "Ejemplo real" block. It retains
 * the production view-model shape so the server-safe marketing preview contract
 * can be derived from the same fields as a live public wishlist. Mirrors the
 * canvas's baby-shower example (`A Wish For.dc.html` §5); prices stay in PEN
 * rather than the canvas's MXN figures since that's the currency the creation
 * wizard actually produces.
 */
export const DEMO_WISHLIST: PublicWishlistViewModel = {
	id: "demo-wishlist",
	slug: "esperando-a-mateo",
	title: "Esperando a Mateo",
	eventType: "baby_shower",
	language: "es",
	currency: "PEN",
	welcomeMessage:
		"Gracias por acompañarnos en la llegada de Mateo. Aquí encontrarás algunas ideas para consentirlo.",
	thankYouMessage: "¡Gracias por tu cariño y por celebrar con nosotros!",
	eventDate: "2026-09-13",
	eventTime: "16:00",
	eventLocation: "Jardín Las Acacias",
	dressCode: null,
	images: [
		{
			url: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9",
			width: 1600,
			height: 1000,
			orientation: "landscape",
		},
		{
			url: "https://images.unsplash.com/photo-1492725764893-90b379c2b6e7",
			width: 1600,
			height: 1000,
			orientation: "landscape",
		},
		{
			url: "https://images.unsplash.com/photo-1519689680058-324335c77eba",
			width: 1600,
			height: 1000,
			orientation: "landscape",
		},
	],
	themeId: "cielo-suave",
	layoutId: "collage-staggered",
	buttonStyle: "pill",
	headingFont: null,
	bodyFont: null,
	showHowItWorks: true,
	categories: [
		{ id: "cat-alimentacion", name: "Alimentación", sortOrder: 0 },
		{ id: "cat-movilidad", name: "Movilidad", sortOrder: 1 },
		{ id: "cat-textil", name: "Textil", sortOrder: 2 },
		{ id: "cat-seguridad", name: "Seguridad", sortOrder: 3 },
		{ id: "cat-higiene", name: "Higiene", sortOrder: 4 },
		{ id: "cat-salud", name: "Salud", sortOrder: 5 },
	],
	gifts: [
		{
			id: "g-biberones",
			name: "Set de biberones (4)",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=300&h=150&fit=crop&auto=format",
			storeName: "Amazon",
			priceAmount: "65.00",
			priceCurrency: "PEN",
			quantityNeeded: 4,
			priority: "high",
			publicNote: null,
			sortOrder: 0,
			categoryId: "cat-alimentacion",
			status: "partial",
			remainingQuantity: 2,
		},
		{
			id: "g-coche",
			name: "Coche de paseo",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=300&h=150&fit=crop&auto=format",
			storeName: "Amazon",
			priceAmount: "480.00",
			priceCurrency: "PEN",
			quantityNeeded: 1,
			priority: "medium",
			publicNote: null,
			sortOrder: 1,
			categoryId: "cat-movilidad",
			status: "available",
			remainingQuantity: 1,
		},
		{
			id: "g-mantita",
			name: "Mantita de algodón",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1519689680058-324335c77eba?w=300&h=150&fit=crop&auto=format",
			storeName: "Ripley",
			priceAmount: "42.00",
			priceCurrency: "PEN",
			quantityNeeded: 1,
			priority: "low",
			publicNote: null,
			sortOrder: 2,
			categoryId: "cat-textil",
			status: "purchased",
			remainingQuantity: 0,
		},
		{
			id: "g-monitor",
			name: "Monitor de bebé",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=300&h=150&fit=crop&auto=format",
			storeName: "Falabella",
			priceAmount: "129.00",
			priceCurrency: "PEN",
			quantityNeeded: 1,
			priority: "medium",
			publicNote: null,
			sortOrder: 3,
			categoryId: "cat-seguridad",
			status: "available",
			remainingQuantity: 1,
		},
		{
			id: "g-silla-auto",
			name: "Silla para el auto",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=300&h=150&fit=crop&auto=format",
			storeName: "Amazon",
			priceAmount: "230.00",
			priceCurrency: "PEN",
			quantityNeeded: 1,
			priority: "high",
			publicNote: null,
			sortOrder: 4,
			categoryId: "cat-movilidad",
			status: "available",
			remainingQuantity: 1,
		},
		{
			id: "g-cobija",
			name: "Cobija de punto",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=300&h=150&fit=crop&auto=format",
			storeName: "Amazon",
			priceAmount: "54.00",
			priceCurrency: "PEN",
			quantityNeeded: 1,
			priority: "low",
			publicNote: null,
			sortOrder: 5,
			categoryId: "cat-textil",
			status: "purchased",
			remainingQuantity: 0,
		},
		{
			id: "g-panales",
			name: "Pañales talla RN (paq. x3)",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1522771930-78848d9293e8?w=300&h=150&fit=crop&auto=format",
			storeName: "Mercado Libre",
			priceAmount: "18.00",
			priceCurrency: "PEN",
			quantityNeeded: 3,
			priority: "medium",
			publicNote: null,
			sortOrder: 6,
			categoryId: "cat-higiene",
			status: "available",
			remainingQuantity: 3,
		},
		{
			id: "g-termometro",
			name: "Termómetro digital",
			productUrl: null,
			imageUrl:
				"https://images.unsplash.com/photo-1542901689-8917f44e3541?w=300&h=150&fit=crop&auto=format",
			storeName: "Oechsle",
			priceAmount: "9.50",
			priceCurrency: "PEN",
			quantityNeeded: 2,
			priority: "low",
			publicNote: null,
			sortOrder: 7,
			categoryId: "cat-salud",
			status: "partial",
			remainingQuantity: 1,
		},
	],
	progress: {
		availableGiftCount: 6,
		purchasedUnits: 5,
		totalUnits: 14,
	},
};
