export const STORE_DISPLAY_NAMES: Record<string, string> = {
	// Peru / LatAm
	"falabella.com.pe": "Falabella",
	"falabella.com": "Falabella",
	"ripley.com.pe": "Ripley",
	"ripley.com": "Ripley",
	"oechsle.pe": "Oechsle",
	"plazavea.com.pe": "Plaza Vea",
	"wong.pe": "Wong",
	"metro.pe": "Metro",
	"sodimac.com.pe": "Sodimac",
	"promart.pe": "Promart",
	"hiraoka.com.pe": "Hiraoka",
	"linio.com.pe": "Linio",
	"estilos.pe": "Estilos",
	"paris.com.pe": "Paris",
	"lapolar.com.pe": "La Polar",
	"tottus.pe": "Tottus",
	"mercadolibre.com.pe": "Mercado Libre",
	"mercadolibre.com": "Mercado Libre",
	"mercadolibre.com.ar": "Mercado Libre",
	"mercadolibre.com.co": "Mercado Libre",
	"mercadolibre.com.mx": "Mercado Libre",
	"mercadolibre.cl": "Mercado Libre",

	// International
	"amazon.com": "Amazon",
	"amazon.co.uk": "Amazon",
	"amazon.de": "Amazon",
	"amazon.fr": "Amazon",
	"amazon.es": "Amazon",
	"amazon.it": "Amazon",
	"amazon.ca": "Amazon",
	"amazon.com.mx": "Amazon",
	"amazon.com.br": "Amazon",
	"ebay.com": "eBay",
	"ebay.co.uk": "eBay",
	"aliexpress.com": "AliExpress",
	"alibaba.com": "Alibaba",
	"etsy.com": "Etsy",
	"walmart.com": "Walmart",
	"target.com": "Target",
	"bestbuy.com": "Best Buy",
	"shein.com": "SHEIN",
	"zara.com": "Zara",
	"hm.com": "H&M",
	"adidas.com": "Adidas",
	"nike.com": "Nike",
	"apple.com": "Apple",
};
